const DEFAULT_PASSWORD="theater58";
function login(){const p=document.getElementById("password").value;const pass=localStorage.getItem("ejshsAdminPassword")||DEFAULT_PASSWORD;if(p===pass){sessionStorage.setItem("ejshsAdmin","1");document.getElementById("login").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");loadAll()}else document.getElementById("loginMsg").textContent="Incorrect password."}
function logout(){sessionStorage.removeItem("ejshsAdmin");location.reload()}
if(sessionStorage.getItem("ejshsAdmin")==="1"){document.getElementById("login").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden")}
const ids=["school","heroTitle","heroText","aboutTitle","aboutText","card1Title","card1Text","card2Title","card2Text","card3Title","card3Text","showTitle","showText","joinText"];
function loadAll(){const d=JSON.parse(localStorage.getItem("ejshsContent")||"null")||{school:"ELWOOD JR. SR. HIGH SCHOOL",heroTitle:"Thespian Troupe 58 & Drama Club",heroText:"Where creativity takes center stage.",aboutTitle:"A place to perform, create & belong.",aboutText:"EJSHS Thespian Troupe 58 & Drama Club brings students together through theater.",card1Title:"Performing",card1Text:"Act, audition, rehearse, and perform.",card2Title:"Tech Crew",card2Text:"Lights, sound, costumes, props, and sets.",card3Title:"Community",card3Text:"Make friends and create together.",showTitle:"Your Next Production",showText:"Production details coming soon.",joinText:"There is a place for you in Drama Club.",email:"ADD-YOUR-SCHOOL-EMAIL-HERE"};ids.forEach(x=>document.getElementById(x+"Input").value=d[x]||"");document.getElementById("emailInput").value=d.email||"";renderEvents()}
function saveContent(){const d=JSON.parse(localStorage.getItem("ejshsContent")||"{}");ids.forEach(x=>d[x]=document.getElementById(x+"Input").value);d.email=document.getElementById("emailInput").value||d.email||"";localStorage.setItem("ejshsContent",JSON.stringify(d));alert("Changes saved! Open the website to see them.")}
function renderEvents(){const es=JSON.parse(localStorage.getItem("ejshsEvents")||"null")||[{title:"Drama Club Meeting",text:"Add your meeting date and room here.",icon:"📅"},{title:"Next Production",text:"Production details coming soon.",icon:"🎭"}];document.getElementById("eventEditor").innerHTML=es.map((e,i)=>`<div class="event-edit"><input data-i="${i}" data-k="icon" value="${e.icon}"><input data-i="${i}" data-k="title" value="${e.title}"><textarea data-i="${i}" data-k="text">${e.text}</textarea><button onclick="removeEvent(${i})">Remove</button></div>`).join("")}
function addEvent(){const es=JSON.parse(localStorage.getItem("ejshsEvents")||"[]");es.push({title:"New Event",text:"Event details here.",icon:"⭐"});localStorage.setItem("ejshsEvents",JSON.stringify(es));renderEvents()}
function removeEvent(i){const es=JSON.parse(localStorage.getItem("ejshsEvents")||"[]");es.splice(i,1);localStorage.setItem("ejshsEvents",JSON.stringify(es));renderEvents()}
function saveEvents(){const es=JSON.parse(localStorage.getItem("ejshsEvents")||"[]");document.querySelectorAll("#eventEditor [data-i]").forEach(el=>es[+el.dataset.i][el.dataset.k]=el.value);localStorage.setItem("ejshsEvents",JSON.stringify(es));alert("Events saved!")}
function saveSettings(){const d=JSON.parse(localStorage.getItem("ejshsContent")||"{}");d.email=document.getElementById("emailInput").value;localStorage.setItem("ejshsContent",JSON.stringify(d));const np=document.getElementById("newPassword").value;if(np)localStorage.setItem("ejshsAdminPassword",np);alert("Settings saved!")}
function showTab(name,btn){document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));document.getElementById(name+"Tab").classList.remove("hidden");document.querySelectorAll(".side").forEach(x=>x.classList.remove("active"));btn.classList.add("active")}
